// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['providers']['Service']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['providers']['Service']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['providers']['Service']['Get'](arg1);
}

export function List() {
  return window['go']['providers']['Service']['List']();
}

export function Update(arg1, arg2) {
  return window['go']['providers']['Service']['Update'](arg1, arg2);
}
