// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {providers} from '../models';

export function Create(arg1:providers.ProviderDto):Promise<providers.Provider>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<providers.Provider>;

export function List():Promise<Array<providers.Provider>>;

export function Update(arg1:string,arg2:Record<string, any>):Promise<providers.Provider>;
