// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['notes']['Service']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['notes']['Service']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['notes']['Service']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['notes']['Service']['List'](arg1);
}

export function Move(arg1, arg2) {
  return window['go']['notes']['Service']['Move'](arg1, arg2);
}

export function Renumber() {
  return window['go']['notes']['Service']['Renumber']();
}

export function Update(arg1, arg2) {
  return window['go']['notes']['Service']['Update'](arg1, arg2);
}
