// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {notes} from '../models';

export function Create(arg1:string,arg2:notes.NoteDto):Promise<notes.Note>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function Get(arg1:string,arg2:string):Promise<notes.Note>;

export function List(arg1:string,arg2:Record<string, any>):Promise<Array<notes.Note>>;

export function Move(arg1:string,arg2:string,arg3:notes.MovePosition):Promise<notes.Note>;

export function Renumber(arg1:string):Promise<Record<string, boolean>>;

export function Update(arg1:string,arg2:string,arg3:Record<string, any>):Promise<notes.Note>;
