// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspaces} from '../models';

export function Create(arg1:workspaces.WorkspaceDto):Promise<workspaces.Workspace>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<workspaces.Workspace>;

export function List():Promise<Array<workspaces.Workspace>>;

export function Update(arg1:string,arg2:Record<string, any>):Promise<workspaces.Workspace>;
