// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {insight} from '../models';

export function Ensure(arg1:string):Promise<insight.Status>;

export function GetStatus(arg1:string):Promise<insight.Status>;

export function Index(arg1:string,arg2:boolean):Promise<insight.SyncResult>;

export function IndexStatus(arg1:string):Promise<insight.IndexStatus>;

export function IsEnabled(arg1:string):Promise<boolean>;

export function Search(arg1:string,arg2:insight.SearchParams):Promise<insight.SearchResult>;

export function SetEnabled(arg1:string,arg2:boolean):Promise<boolean>;

export function Stop(arg1:string):Promise<Record<string, any>>;

export function Sync(arg1:string):Promise<insight.SyncResult>;
