// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// NOTE: stub until `wails generate` runs with internal/insight wired in app.go.

export function Ensure(arg1) {
  return window['go']['insight']['Service']['Ensure'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['insight']['Service']['GetStatus'](arg1);
}

export function Stop(arg1) {
  return window['go']['insight']['Service']['Stop'](arg1);
}

export function Sync(arg1, arg2) {
  return window['go']['insight']['Service']['Sync'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['insight']['Service']['Search'](arg1, arg2);
}

export function IsEnabled(arg1) {
  return window['go']['insight']['Service']['IsEnabled'](arg1);
}

export function SetEnabled(arg1, arg2) {
  return window['go']['insight']['Service']['SetEnabled'](arg1, arg2);
}
