// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ensure(arg1) {
  return window['go']['insight']['Service']['Ensure'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['insight']['Service']['GetStatus'](arg1);
}

export function Index(arg1, arg2) {
  return window['go']['insight']['Service']['Index'](arg1, arg2);
}

export function IndexStatus(arg1) {
  return window['go']['insight']['Service']['IndexStatus'](arg1);
}

export function IsEnabled(arg1) {
  return window['go']['insight']['Service']['IsEnabled'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['insight']['Service']['Search'](arg1, arg2);
}

export function SetEnabled(arg1, arg2) {
  return window['go']['insight']['Service']['SetEnabled'](arg1, arg2);
}

export function Stop(arg1) {
  return window['go']['insight']['Service']['Stop'](arg1);
}

export function Sync(arg1) {
  return window['go']['insight']['Service']['Sync'](arg1);
}
