// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// NOTE: stub until `wails generate` runs with internal/insight wired in app.go.

export function Ensure(arg1:string):Promise<Record<string, any>>;

export function GetStatus(arg1:string):Promise<Record<string, any>>;

export function Stop(arg1:string):Promise<Record<string, any>>;

export function Sync(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function Search(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function IsEnabled(arg1:string):Promise<boolean>;

export function SetEnabled(arg1:string,arg2:boolean):Promise<boolean>;
