// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['categories']['Service']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['categories']['Service']['Delete'](arg1);
}

export function List() {
  return window['go']['categories']['Service']['List']();
}

export function Rename(arg1, arg2) {
  return window['go']['categories']['Service']['Rename'](arg1, arg2);
}
