// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {categories} from '../models';

export function Create(arg1:categories.CategoryDto):Promise<categories.Category>;

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<categories.Category>>;

export function Rename(arg1:string,arg2:string):Promise<categories.Category>;
