// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['categories']['Service']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['categories']['Service']['Delete'](arg1, arg2);
}

export function List(arg1) {
  return window['go']['categories']['Service']['List'](arg1);
}

export function Rename(arg1, arg2, arg3) {
  return window['go']['categories']['Service']['Rename'](arg1, arg2, arg3);
}
