// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {files} from '../models';
import {context} from '../models';

export function GetStat(arg1:string,arg2:string):Promise<files.GetStatData>;

export function ListDir(arg1:string,arg2:string):Promise<files.ListDirData>;

export function PickDirectory(arg1:string,arg2:string):Promise<string>;

export function ReadFile(arg1:string,arg2:string,arg3:any):Promise<files.ReadFileData>;

export function SetAppContext(arg1:context.Context):Promise<void>;
