// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {messages} from '../models';

export function LoadHistory(arg1:string,arg2:string):Promise<Array<messages.UIMessage>>;
