// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadHistory(arg1, arg2) {
  return window['go']['messages']['Service']['LoadHistory'](arg1, arg2);
}

export function PreviewRevertMessages(arg1, arg2, arg3) {
  return window['go']['messages']['Service']['PreviewRevertMessages'](arg1, arg2, arg3);
}

export function RevertMessages(arg1, arg2, arg3, arg4) {
  return window['go']['messages']['Service']['RevertMessages'](arg1, arg2, arg3, arg4);
}
