// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chats} from '../models';

export function Create(arg1:string,arg2:chats.ChatDto):Promise<chats.Chat>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function Get(arg1:string,arg2:string):Promise<chats.Chat>;

export function List(arg1:string):Promise<Array<chats.Chat>>;

export function Update(arg1:string,arg2:string,arg3:Record<string, any>):Promise<chats.Chat>;
