// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:string,arg2:models.ModelDto):Promise<models.Model>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function List(arg1:string):Promise<Array<models.Model>>;

export function Update(arg1:string,arg2:string,arg3:Record<string, any>):Promise<models.Model>;
