// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CancelStream(arg1:string):Promise<void>;

export function SetAppContext(arg1:context.Context):Promise<void>;

export function StartStream(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
