// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['stream']['ChatStreamService']['CancelStream'](arg1);
}

export function SetAppContext(arg1) {
  return window['go']['stream']['ChatStreamService']['SetAppContext'](arg1);
}

export function StartStream(arg1, arg2, arg3, arg4) {
  return window['go']['stream']['ChatStreamService']['StartStream'](arg1, arg2, arg3, arg4);
}
