// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetAppContext(arg1) {
  return window['go']['stream']['HitlWatchService']['SetAppContext'](arg1);
}

export function StartWatch() {
  return window['go']['stream']['HitlWatchService']['StartWatch']();
}

export function StopWatch(arg1) {
  return window['go']['stream']['HitlWatchService']['StopWatch'](arg1);
}
