// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function SetAppContext(arg1:context.Context):Promise<void>;

export function StartWatch():Promise<string>;

export function StopWatch(arg1:string):Promise<void>;
