// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// NOTE: stub until `wails generate` runs with internal/stream wired in app.go.
import {context} from '../models';

export function SetAppContext(arg1:context.Context):Promise<void>;

export function StartWatch(arg1:string):Promise<string>;

export function StopWatch(arg1:string):Promise<void>;
