// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
// NOTE: stub until `wails generate` runs with internal/stream wired in app.go.

export function SetAppContext(arg1) {
  return window['go']['stream']['InsightWatchService']['SetAppContext'](arg1);
}

export function StartWatch(arg1) {
  return window['go']['stream']['InsightWatchService']['StartWatch'](arg1);
}

export function StopWatch(arg1) {
  return window['go']['stream']['InsightWatchService']['StopWatch'](arg1);
}
