// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stream} from '../models';
import {context} from '../models';

export function CancelRun(arg1:string,arg2:string,arg3:string):Promise<stream.RunInfo>;

export function GetRun(arg1:string,arg2:string,arg3:string):Promise<stream.RunInfo>;

export function ListRuns(arg1:string,arg2:string):Promise<Array<stream.RunInfo>>;

export function SetAppContext(arg1:context.Context):Promise<void>;

export function StartRun(arg1:string,arg2:string,arg3:string):Promise<stream.StartRunResult>;

export function UnwatchRun(arg1:string):Promise<void>;

export function WatchRun(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;
