// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun(arg1, arg2, arg3) {
  return window['go']['stream']['RunStreamService']['CancelRun'](arg1, arg2, arg3);
}

export function GetRun(arg1, arg2, arg3) {
  return window['go']['stream']['RunStreamService']['GetRun'](arg1, arg2, arg3);
}

export function ListRuns(arg1, arg2) {
  return window['go']['stream']['RunStreamService']['ListRuns'](arg1, arg2);
}

export function SetAppContext(arg1) {
  return window['go']['stream']['RunStreamService']['SetAppContext'](arg1);
}

export function StartRun(arg1, arg2, arg3) {
  return window['go']['stream']['RunStreamService']['StartRun'](arg1, arg2, arg3);
}

export function UnwatchRun(arg1) {
  return window['go']['stream']['RunStreamService']['UnwatchRun'](arg1);
}

export function WatchRun(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['stream']['RunStreamService']['WatchRun'](arg1, arg2, arg3, arg4, arg5);
}
