// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetAppContext(arg1) {
  return window['go']['stream']['ShellExecWatchService']['SetAppContext'](arg1);
}

export function StartWatch(arg1) {
  return window['go']['stream']['ShellExecWatchService']['StartWatch'](arg1);
}

export function StopWatch(arg1) {
  return window['go']['stream']['ShellExecWatchService']['StopWatch'](arg1);
}
