// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decide(arg1, arg2) {
  return window['go']['shell']['Service']['Decide'](arg1, arg2);
}

export function PendingApprovals() {
  return window['go']['shell']['Service']['PendingApprovals']();
}
