// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shell} from '../models';

export function Decide(arg1:string,arg2:string):Promise<shell.DecideResult>;

export function PendingApprovals():Promise<Array<shell.PendingApproval>>;
