// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListServers(arg1) {
  return window['go']['mcp']['Service']['ListServers'](arg1);
}

export function SetEnabled(arg1, arg2, arg3) {
  return window['go']['mcp']['Service']['SetEnabled'](arg1, arg2, arg3);
}
