// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';

export function ListServers(arg1:string):Promise<mcp.ListResult>;

export function SetEnabled(arg1:string,arg2:string,arg3:boolean):Promise<mcp.SetResult>;
