// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hitl} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Create(arg1:Record<string, any>):Promise<hitl.HitlRequest>;

export function GetByID(arg1:string):Promise<hitl.HitlRequest>;

export function ListPending():Promise<Array<hitl.HitlRequest>>;

export function SubmitResponse(arg1:string,arg2:Record<string, any>):Promise<hitl.HitlRequest>;
