// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['hitl']['Service']['Cancel'](arg1);
}

export function Create(arg1) {
  return window['go']['hitl']['Service']['Create'](arg1);
}

export function GetByID(arg1) {
  return window['go']['hitl']['Service']['GetByID'](arg1);
}

export function ListPending() {
  return window['go']['hitl']['Service']['ListPending']();
}

export function SubmitResponse(arg1, arg2) {
  return window['go']['hitl']['Service']['SubmitResponse'](arg1, arg2);
}
