// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultProvider() {
  return window['go']['settings']['Service']['GetDefaultProvider']();
}

export function GetValue(arg1) {
  return window['go']['settings']['Service']['GetValue'](arg1);
}

export function SetDefaultProvider(arg1, arg2) {
  return window['go']['settings']['Service']['SetDefaultProvider'](arg1, arg2);
}

export function SetValue(arg1, arg2) {
  return window['go']['settings']['Service']['SetValue'](arg1, arg2);
}
