// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetDefaultProvider():Promise<settings.DefaultProvider>;

export function GetValue(arg1:string):Promise<settings.SettingValue>;

export function SetDefaultProvider(arg1:string,arg2:string):Promise<settings.DefaultProvider>;

export function SetValue(arg1:string,arg2:string):Promise<settings.SettingValue>;
