name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - name: ESLint
        run: bun eslint . --cache

      - name: Format Check
        run: bun oxfmt src/ --check

      - name: Type Check
        run: bun run type-check

      - name: Build
        run: bun run build-only
